=== IOCOTech/Angular-Framework/src/environments/config/config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "IAuthenticationConfig": {
            "properties": {
                "authority": {
                    "type": "string"
                },
                "clientId": {
                    "type": "string"
                },
                "navigateToLoginRequestUrl": {
                    "type": "boolean"
                },
                "postLogoutRedirectUri": {
                    "type": "string"
                },
                "redirectUri": {
                    "type": "string"
                },
                "validateAuthority": {
                    "type": "boolean"
                }
            },
            "required": [
                "authority",
                "clientId",
                "navigateToLoginRequestUrl",
                "postLogoutRedirectUri",
                "redirectUri",
                "validateAuthority"
            ],
            "type": "object"
        },
        "ILogging": {
            "properties": {
                "errorLogTo": {
                    "default": "error",
                    "description": "Severity of error levels that should be logged:",
                    "examples": [
                        "console",
                        "appInsights"
                    ],
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "loggingLevel": {
                    "anyOf": [
                        {
                            "enum": [
                                1,
                                2,
                                3,
                                4
                            ],
                            "type": "number"
                        },
                        {
                            "type": "string"
                        }
                    ],
                    "default": "error",
                    "description": "Severity of error levels that should be logged:",
                    "examples": [
                        "info",
                        "warning",
                        "error",
                        "critical"
                    ]
                }
            },
            "required": [
                "errorLogTo",
                "loggingLevel"
            ],
            "type": "object"
        }
    },
    "properties": {
        "apiBaseURL": {
            "type": "string"
        },
        "appInsightsKey": {
            "type": "string"
        },
        "authentication": {
            "$ref": "#/definitions/IAuthenticationConfig"
        },
        "logging": {
            "$ref": "#/definitions/ILogging"
        }
    },
    "required": [
        "apiBaseURL",
        "appInsightsKey",
        "authentication",
        "logging"
    ],
    "type": "object"
}

=== IOCOTech/Angular-Framework/src/config.json
{
    "$schema": "./environments/config/config.schema.json",
    "apiBaseURL": "http://localhost:57418",
    "appInsightsKey": "211f0722-a9f3-4c1c-b45f-4f5206a0dfbe",
    "authentication": {
        "clientId": "714270ac-cd7a-41eb-a4f6-583e6c850bf2",
        "authority": "https://{domain}.b2clogin.com/12345c1a-207d-45fc-aec1-19cb93423c20/B2C_1A_signin",
        "validateAuthority": false,
        "redirectUri": "http://localhost:4200/oid-redirect",
        "postLogoutRedirectUri": "http://localhost:4200",
        "navigateToLoginRequestUrl": true
    },
    "logging": {
        "errorLogTo": [
            "console",
            "appInsights"
        ],
        "loggingLevel": "info"
    }
}

=== IOCOTech/Angular-Framework/src/environments/config/mock/config.json
{
  "$schema": "./environments/config/config.schema.json",
  "apiBaseURL": "http://localhost:57418",
  "appInsightsKey": "0000000-0000-0000-0000-000000000000",
  "authentication": {
      "clientId": "0000000-0000-0000-0000-000000000000",
      "authority": "https://{replace-with-organization}.b2clogin.com/0000000-0000-0000-0000-000000000000/B2C_1_Default",
      "validateAuthority": false,
      "redirectUri": "https://localhost:4200/oid-redirect",
      "postLogoutRedirectUri": "https://localhost:4200",
      "navigateToLoginRequestUrl": true
  },
  "logging": {
      "errorLogTo": [
          "console",
          "appInsights"
      ],
      "loggingLevel": "info"
  }
}

=== IOCOTech/Angular-Framework/src/environments/config/dev/config.json
{
    "$schema": "../../../environments/config/config.schema.json",
    "apiBaseURL": "https://localhost:44386",
    "appInsightsKey": "211f0722-a9f3-4c1c-b45f-123206a0dfbe",
  "authentication": {
    "clientId": "714270ac-cd7a-41eb-a4f6-583e6c850bf2",
    "authority": "https://{{app-name}}.b2clogin.com/{{tenantId}}/B2C_1A_signin",
    "validateAuthority": false,
    "redirectUri": "http://localhost:4200/oid-redirect",
    "postLogoutRedirectUri": "http://localhost:4200",
    "navigateToLoginRequestUrl": true
  },
    "logging": {
        "errorLogTo": [
            "console",
            "appInsights"
        ],
        "loggingLevel": "info"
    }
}
